tasks:

# tbd task to create provider/instrument/wavelength ; if not existing the submit will fail
  - source: createinvestigation.py
    product:
      nb: products/createinvestigation.ipynb
    params:
      hsds_investigation: "{{hsds_investigation}}"
      keycloak_server_url: "{{keycloak_server_url}}"
      keycloak_client_id: "{{keycloak_client_id}}"
      keycloak_realm_name: "{{keycloak_realm_name}}"
      hs_admin_username: "{{hs_admin}}"
      hs_admin_password: "{{hs_adminpassword}}"

  - source: ../tasks/read_metadata.py
    product: 
      nb: "products/read_metadata.ipynb"
      data: "products/metadata.xlsx"
    params:
      input4import: "{{input4import}}"

  - source: ../tasks/match_metadata.py
    product: 
      nb: "products/match_metadata.ipynb"
      metadata_name: "products/metadata_name.xlsx"
      metadata_file: "products/metadata_file.xlsx"

  - source: ../tasks/templates_read.py
    product: 
      nb: "products/templates_read.ipynb"
      h5: "products\\templates_read.h5"
      xlsx: "products\\templates_read.xlsx"
    params:
      config_templates: "{{config_templates}}"
      config_root: "{{config_root}}"

  - source: templates_import.py
    product:
      data: products/templates_import.log
      nb: products/templates_import.ipynb
    params:
      config_root: "{{config_root}}"
      ramandb_api: "{{ramandb_api}}"
      hsds_investigation: "{{hsds_investigation}}"
      keycloak_server_url: "{{keycloak_server_url}}"
      keycloak_client_id: "{{keycloak_client_id}}"
      keycloak_realm_name: "{{keycloak_realm_name}}"
      hs_username: "{{hs_username}}"
      hs_password: "{{hs_password}}"
      dry_run: False

  - source: auth.py
    product:
      nb: products/auth.ipynb
      domains: products/domains.json
    params:
      keycloak_server_url: "{{keycloak_server_url}}"
      keycloak_client_id: "{{keycloak_client_id}}"
      keycloak_realm_name: "{{keycloak_realm_name}}"
      hs_username: "{{hs_username}}"
      hs_password: "{{hs_password}}"
      hs_endpoint: "{{hs_endpoint}}"
      ramandb_api: "{{ramandb_api}}"

  - source: task_export2solr.py
    product:
      data: "{{charisma_json}}_kc_{{hsds_investigation}}.json"
      nb: products/task_export2solr.ipynb
    params:
      hsds_investigation: "{{hsds_investigation}}"
      keycloak_server_url: "{{keycloak_server_url}}"
      keycloak_client_id: "{{keycloak_client_id}}"
      keycloak_realm_name: "{{keycloak_realm_name}}"
      hs_username: "{{hs_username}}"
      hs_password: "{{hs_password}}"

  - source: task_solrquery.py
    product:
      nb:  products/task_solrquery.ipynb
    params:
      keycloak_server_url: "{{keycloak_server_url}}"
      keycloak_client_id: "{{keycloak_client_id}}"
      keycloak_realm_name: "{{keycloak_realm_name}}"
      hs_username: "{{hs_username}}"
      hs_password: "{{hs_password}}"
      query_file: "{{query_file}}"
