meta:
    extract_upstream: False

tasks:

  - source: spectraframe_load.py
    name: "spectraframe_[[key]]"
    upstream: []
    product: 
      nb: "{{config_output}}/[[key]]/spectraframe_load.ipynb"
      h5: "{{config_output}}/[[key]]/spectraframe_load.h5"
      xlsx: "{{config_output}}/[[key]]/spectraframe_load.xlsx"
    params:
      config_templates: "{{config_templates}}"
      config_root: "{{config_root}}"
    grid:
      key: ["0101","0401","0402","0601","0701","0702","0801","01001","01201","01202"]

  - source: spectraframe_calibrate.py
    name: "spectracal_[[key]]"    
    product: 
      nb: "{{config_output}}_{{fit_ne_peaks}}/[[key]]/spectracal.ipynb"
      calmodels: "{{config_output}}_{{fit_ne_peaks}}/[[key]]/calmodels"
    upstream: "spectraframe_*"      
    params:
      config_templates: "{{config_templates}}"
      config_root: "{{config_root}}"
      neon_tag: "{{ne_tag}}"
      si_tag: "{{si_tag}}"
      pst_tag: "{{pst_tag}}"
      apap_tag: "{{apap_tag}}"
      fit_neon_peaks: "{{fit_ne_peaks}}"   
    grid:
      key: ["0101","0601","0701","0702","0801","01001","01201","01202"]

 
  - source: calibration_verify.py
    upstream: ["spectraframe_*","spectracal_*"]
    product: 
      nb: "{{config_output}}_{{fit_ne_peaks}}/assessment/calibration_verify.html"
    params:
      config_templates: "{{config_templates}}"
      config_root: "{{config_root}}"
    nbconvert_export_kwargs:
        # optionally hide the code from the report
        exclude_input: True            
 