tasks:

  - source: templates_read.py
    product: 
      nb: "{{config_output}}/templates_read.ipynb"
      h5: "{{config_output}}\\templates_read.h5"
      xlsx: "{{config_output}}\\templates_read.xlsx"
    params:
      config_templates: "{{config_templates}}"
      config_root: "{{config_root}}"

  - source: templates_load.py
    product: 
      nb: "{{config_output}}/templates_load.ipynb"
      data: "{{config_output}}/templates_load"
    params:
      config_root: "{{config_root}}"    
      neon_tag: "{{ne_tag}}"
      si_tag: "{{si_tag}}"
      pst_tag: "{{pst_tag}}"
      test_tags: "{{test_tags}}"
      ti_tags: "{{ti_tags}}"
      apap_tags: "{{apap_tags}}"

  - source: templates_calibration.py
    product: 
      nb: "{{config_output}}/templates_calibration.ipynb"
      data: "{{config_output}}/templates_calibration"
    params:
      config_root: "{{config_root}}"    
      neon_tag: "{{ne_tag}}"
      si_tag: "{{si_tag}}"
      pst_tag: "{{pst_tag}}"
      test_tags: "{{test_tags}}" 
      fit_ne_peaks: "{{fit_ne_peaks}}"

  - source: templates_assessment.py
    name: templates_assessment-[[pst_tag]]  
    product: 
      nb: "products/templates_assessment-[[pst_tag]].ipynb"
      hnswlib: "{{config_output}}/templates_assessment-[[pst_tag]]"
    params:
      neon_tag: "{{ne_tag}}"
      si_tag: "{{si_tag}}"
    grid:
        pst_tag: ["PST","CAL","S0N","APAP","S0B"]
         